# Generated by Django 3.1.7 on 2021-04-28 23:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('viewrateusers', '0004_auto_20210428_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='phnumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
