# Generated by Django 3.1.7 on 2021-04-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewrateusers', '0005_auto_20210428_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='phnumber',
            field=models.CharField(max_length=11),
        ),
    ]
