# Generated by Django 3.1.7 on 2021-04-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDetails',
            fields=[
                ('communityid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('addr1', models.CharField(max_length=250)),
                ('addr2', models.CharField(max_length=250)),
                ('phnumber', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('avgrent', models.CharField(max_length=500)),
                ('communitypictureurl', models.CharField(max_length=2083)),
            ],
            options={
                'db_table': 'communitydetails',
            },
        ),
    ]
