# Generated by Django 3.1.7 on 2021-04-24 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('communityuserid', models.CharField(max_length=50)),
                ('communityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.communitydetails')),
            ],
            options={
                'db_table': 'communityuserdetails',
                'unique_together': {('communityuserid', 'name')},
            },
        ),
    ]
