# Generated by Django 3.1.7 on 2021-04-04 20:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usersdata',
            fields=[
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phnumber', models.IntegerField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('addr1', models.CharField(max_length=250)),
                ('addr2', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('workinfo', models.CharField(max_length=500)),
                ('profilepicurl', models.CharField(max_length=2083)),
            ],
            options={
                'db_table': 'usersdata',
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingid', models.IntegerField()),
                ('peerrating', models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('guestrating', models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('communityrating', models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findroommate.usersdata')),
            ],
            options={
                'db_table': 'userrating',
                'unique_together': {('userid', 'ratingid')},
            },
        ),
        migrations.CreateModel(
            name='Userpreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefid', models.IntegerField()),
                ('preflocation', models.CharField(max_length=50)),
                ('prefsex', models.CharField(max_length=10)),
                ('usersex', models.CharField(max_length=10)),
                ('budget', models.IntegerField()),
                ('cleanliness', models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('booze_smoke', models.BooleanField(default=False)),
                ('prefapartment1', models.CharField(max_length=50)),
                ('prefapartment2', models.CharField(max_length=50)),
                ('prefapartment3', models.CharField(max_length=50)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findroommate.usersdata')),
            ],
            options={
                'db_table': 'userpreference',
                'unique_together': {('userid', 'prefid')},
            },
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentid', models.IntegerField()),
                ('comment', models.CharField(max_length=3000)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findroommate.usersdata')),
            ],
            options={
                'db_table': 'usercomments',
                'unique_together': {('userid', 'commentid')},
            },
        ),
    ]
