# Generated by Django 3.1.7 on 2021-04-21 22:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewrateusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultantTempUserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('avgrating', models.IntegerField()),
                ('compatibilityscore', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('profilepicurl', models.CharField(max_length=2083)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewrateusers.usersdata')),
            ],
            options={
                'db_table': 'resultanttempusertable',
            },
        ),
    ]
