# Generated by Django 3.1.7 on 2021-04-24 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findroommate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultanttempusertable',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resultanttempusertable',
            name='avgrating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resultanttempusertable',
            name='compatibilityscore',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='resultanttempusertable',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resultanttempusertable',
            name='profilepicurl',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
